package com.chat.common.protocol;

public enum PacketType {
    // Auth Packets
    REGISTER_REQUEST,
    REGISTER_RESPONSE,
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    LOGOUT_REQUEST,
    LOGOUT_RESPONSE,

    // User Operations
    SEARCH_USER_REQUEST,
    SEARCH_USER_RESPONSE,
    UPDATE_PROFILE_REQUEST,
    UPDATE_PROFILE_RESPONSE,
    USER_STATUS_CHANGE,
    GET_USER_LIST_REQUEST,
    GET_USER_LIST_RESPONSE,

    // Chat Packets
    CHAT_MESSAGE,
    MESSAGE_DELIVERED,
    MESSAGE_READ,
    TYPING_INDICATOR,
    GET_CHAT_HISTORY_REQUEST,
    GET_CHAT_HISTORY_RESPONSE,

    // Group Packets
    CREATE_GROUP_REQUEST,
    CREATE_GROUP_RESPONSE,
    GET_USER_GROUPS_REQUEST,
    GET_USER_GROUPS_RESPONSE,
    GROUP_MESSAGE,

    // File Packets
    FILE_UPLOAD_REQUEST,
    FILE_UPLOAD_RESPONSE,
    FILE_DOWNLOAD_REQUEST,
    FILE_DOWNLOAD_RESPONSE,

    // General Response
    ERROR_RESPONSE,
    HEARTBEAT
}
